[[entries]]
id = "8b34930f-7112-4ecc-b18e-deb740ca42ac"
type = "feature"
description = "Add a pre-commit hook for pydoc-markdown."
author = "@RomainTT"
pr = "https://github.com/NiklasRosenstein/pydoc-markdown/pull/298"

[[entries]]
id = "cbec74c9-4d3f-4c65-9d57-73d024ce17fa"
type = "improvement"
description = "Bump minimum version of `databind.core` and `databind.json` to `^4.4.2` to ensure Python 3.12 support"
author = "@NiklasRosenstein"
pr = "https://github.com/NiklasRosenstein/pydoc-markdown/pull/304"

[[entries]]
id = "5e25fdde-ec38-42a7-9ab1-7066e4af6d81"
type = "breaking change"
description = "Drop Python 3.7 compatibility"
author = "@NiklasRosenstein"
pr = "https://github.com/NiklasRosenstein/pydoc-markdown/pull/304"
